version: '3.8'

services:
  webserver:
    image: php:psql_01
      #volumes:
      #- /var/www/html/midas:/var/www/html/  # Mount your PHP application directory
    ports:
      - "80:80"  # Expose port 80 on the host
    depends_on:
      - postgres  # Assuming PostgreSQL service is defined in the same file

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"

